language: python
python:
    - "3.6"
env:
  - DJANGO_VERSION=2.1.3
  - DJANGO_SETTINGS_MODULE=testing.settings

install:
    - pip install -r requirements.txt

script:
    -cd testing
    - py.test --cov
